name: pruebas ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo
        run: echo "Hola mundo"
      - name: fecha
        run: date
      - name: Checkoout repositorio
        uses: actions/checkout@v4
      - name: Listar archivos
        run: ls -R